### ISSUE TITLE
iOS accent color is set to light mode

### ISSUE THREAD

**Issue by taciturnaxolotl** [capjamesg/web-reader#1]
Hi! I live the project so far!!! I noticed one small issue in that the accent color is still in light mode while the rest of the ui transforms. 

I believe you just need to set the theme color tag properly with a css variable that changes with a media query. 

```html
<meta name = "theme-color" content = "#000000">
```

![image](https://github.com/user-attachments/assets/aa14d486-4d15-4d77-bfb1-e8d67fba9abf)

**Comment by capjamesg** [comment]
Oooh, that is a really good call! Let me add that.

**Comment by capjamesg** [comment]
I have made this change and pushed it to production. Let me know if everything appears as expected!

**Comment by taciturnaxolotl** [comment]
works perfectly! love the purple accent ^-^
